{
  "uid" : "56d54721299b1de4",
  "name" : "test_xfail_unexpected_pass___",
  "fullName" : "vkr_project_tests.test_attach#test_xfail_unexpected_pass___",
  "historyId" : "49075655edb191ab4db2f61f5fb1b8be",
  "time" : {
    "start" : 1649448589969,
    "stop" : 1649448589969,
    "duration" : 0
  },
  "description" : "this test is an xfail that will be marked as unexpected success",
  "descriptionHtml" : "<p>this test is an xfail that will be marked as unexpected success</p>\n",
  "status" : "skipped",
  "statusMessage" : "XFAIL this test is expecting failure\n\nAssertionError: assert False",
  "statusTrace" : "@pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_unexpected_pass___():\n        \"\"\"this test is an xfail that will be marked as unexpected success\"\"\"\n>       assert False\nE       assert False\n\nvkr_project_tests/test_attach.py:24: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(condition=<function <lambda> at 0x7f2c493f8700>, reason='this test is expecting failure')"
  }, {
    "name" : "parentSuite",
    "value" : "vkr_project_tests"
  }, {
    "name" : "suite",
    "value" : "test_attach"
  }, {
    "name" : "host",
    "value" : "fv-az127-553"
  }, {
    "name" : "thread",
    "value" : "2421-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "vkr_project_tests.test_attach"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 2,
        "passed" : 1,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "5e6e3dc55eac16f0",
        "reportUrl" : "https://YaroslavS1.github.io/VKR_project/83//#testresult/5e6e3dc55eac16f0",
        "status" : "skipped",
        "statusDetails" : "XFAIL this test is expecting failure\n\nAssertionError: assert False",
        "time" : {
          "start" : 1649448213078,
          "stop" : 1649448213078,
          "duration" : 0
        }
      }, {
        "uid" : "1c3d5b755d3367a4",
        "reportUrl" : "https://YaroslavS1.github.io/VKR_project/82//#testresult/1c3d5b755d3367a4",
        "status" : "passed",
        "statusDetails" : "XPASS this test is expecting failure",
        "time" : {
          "start" : 1649448044373,
          "stop" : 1649448044373,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail(condition=<function <lambda> at 0x7f2c493f8700>, reason='this test is expecting failure')" ]
  },
  "source" : "56d54721299b1de4.json",
  "parameterValues" : [ ]
}