{
  "uid" : "2b28b5a87181c1ca",
  "name" : "test_count_summary_cost_ads",
  "fullName" : "vkr_project_tests.test_attach#test_count_summary_cost_ads",
  "historyId" : "510998b91d3f9014f7c6dfe23bddced0",
  "time" : {
    "start" : 1649586384141,
    "stop" : 1649586384574,
    "duration" : 433
  },
  "description" : "Calculation of the total cost of advertising",
  "descriptionHtml" : "<p>Calculation of the total cost of advertising</p>\n",
  "status" : "passed",
  "statusMessage" : "XPASS this test is expecting failure",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "description" : "Calculation of the total cost of advertising",
    "status" : "passed",
    "statusMessage" : "XPASS this test is expecting failure",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "d2416df149554098",
      "name" : "eb68cac6-ac43-4027-83cd-a1b3eff3346f-attachment.html",
      "source" : "d2416df149554098.html",
      "type" : "text/html",
      "size" : 3687249
    }, {
      "uid" : "fd9346c128bc46d1",
      "name" : "stdout",
      "source" : "fd9346c128bc46d1.txt",
      "type" : "text/plain",
      "size" : 90
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(condition=<function <lambda> at 0x7ffaf437c310>, reason='this test is expecting failure')"
  }, {
    "name" : "parentSuite",
    "value" : "vkr_project_tests"
  }, {
    "name" : "suite",
    "value" : "test_attach"
  }, {
    "name" : "host",
    "value" : "fv-az82-279"
  }, {
    "name" : "thread",
    "value" : "2279-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "vkr_project_tests.test_attach"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 4,
        "passed" : 1,
        "unknown" : 0,
        "total" : 5
      },
      "items" : [ {
        "uid" : "b328d99fab9d502f",
        "reportUrl" : "https://YaroslavS1.github.io/VKR_project/89//#testresult/b328d99fab9d502f",
        "status" : "skipped",
        "statusDetails" : "XFAIL this test is expecting failure\n\nFileNotFoundError: [Errno 2] No such file or directory: 'temp.name'",
        "time" : {
          "start" : 1649586031003,
          "stop" : 1649586031398,
          "duration" : 395
        }
      }, {
        "uid" : "aad32a1c16c5f9b2",
        "reportUrl" : "https://YaroslavS1.github.io/VKR_project/88//#testresult/aad32a1c16c5f9b2",
        "status" : "skipped",
        "statusDetails" : "XFAIL this test is expecting failure\n\nFileNotFoundError: [Errno 2] No such file or directory: '../case/cashe.csv'",
        "time" : {
          "start" : 1649585828371,
          "stop" : 1649585828372,
          "duration" : 1
        }
      }, {
        "uid" : "a3ad293c5fa92e3b",
        "reportUrl" : "https://YaroslavS1.github.io/VKR_project/87//#testresult/a3ad293c5fa92e3b",
        "status" : "skipped",
        "statusDetails" : "XFAIL this test is expecting failure\n\nFileNotFoundError: [Errno 2] No such file or directory: '../case/cashe.csv'",
        "time" : {
          "start" : 1649585048630,
          "stop" : 1649585048631,
          "duration" : 1
        }
      }, {
        "uid" : "be707adf5fe5d8dd",
        "reportUrl" : "https://YaroslavS1.github.io/VKR_project/86//#testresult/be707adf5fe5d8dd",
        "status" : "skipped",
        "statusDetails" : "XFAIL this test is expecting failure\n\nFileNotFoundError: [Errno 2] No such file or directory: '../case/cashe.csv'",
        "time" : {
          "start" : 1649530694123,
          "stop" : 1649530694125,
          "duration" : 2
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail(condition=<function <lambda> at 0x7ffaf437c310>, reason='this test is expecting failure')" ]
  },
  "source" : "2b28b5a87181c1ca.json",
  "parameterValues" : [ ]
}